name: CI Pipeline

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck p7zip-full

    - name: Install MSP430 GCC Toolchain
      run: | 

    - name: Build the project
      run: make all

    - name: Run Cppcheck
      run: make cppcheck
